info:
  namespace: vspe_trinkets

font_images:
  accuracy:
    path: groups/accuracy.png
    scale_ratio: 9
    y_position: 8
    symbol: âŸ

  attack_damage:
    path: groups/attack_damage.png
    scale_ratio: 9
    y_position: 8
    symbol: âš”

  attack_speed:
    path: groups/attack_speed.png
    scale_ratio: 9
    y_position: 8
    symbol: â©

  cooldown_reduction:
    path: groups/cooldown_reduction.png
    scale_ratio: 9
    y_position: 8
    symbol: â³

  crit_chance:
    path: groups/crit_chance.png
    scale_ratio: 9
    y_position: 8
    symbol: âœ§

  crit_damage:
    path: groups/crit_damage.png
    scale_ratio: 9
    y_position: 8
    symbol: â–

  damage_reduction:
    path: groups/damage_reduction.png
    scale_ratio: 9
    y_position: 8
    symbol: ğŸ›¡

  defense:
    path: groups/defense.png
    scale_ratio: 9
    y_position: 8
    symbol: â›¨

  dodge:
    path: groups/dodge.png
    scale_ratio: 9
    y_position: 8
    symbol: â¤´

  exp_gain:
    path: groups/exp_gain.png
    scale_ratio: 9
    y_position: 8
    symbol: ğŸ“–

  health_regen:
    path: groups/health_regen.png
    scale_ratio: 9
    y_position: 8
    symbol: â¤

  life_steal:
    path: groups/life_steal.png
    scale_ratio: 9
    y_position: 8
    symbol: ğŸ©¸

  luck:
    path: groups/luck.png
    scale_ratio: 9
    y_position: 8
    symbol: ğŸ€

  magic_damage:
    path: groups/magic_damage.png
    scale_ratio: 9
    y_position: 8
    symbol: ğŸ”®

  mana:
    path: groups/mana.png
    scale_ratio: 9
    y_position: 8
    symbol: ğŸ”µ

  mana_regen:
    path: groups/mana_regen.png
    scale_ratio: 9
    y_position: 8
    symbol: ğŸ’§

  movement_speed:
    path: groups/movement_speed.png
    scale_ratio: 9
    y_position: 8
    symbol: ğŸƒ

  range:
    path: groups/range.png
    scale_ratio: 9
    y_position: 8
    symbol: ğŸ¯

  sensing:
    path: groups/sensing.png
    scale_ratio: 9
    y_position: 8
    symbol: ğŸ”

  stealth:
    path: groups/stealth.png
    scale_ratio: 9
    y_position: 8
    symbol: ğŸ•µ